[2023-03-04T11:52:50.921+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: first-dag-v2.task-2 manual__2023-03-04T11:50:47.231477+00:00 [queued]>
[2023-03-04T11:52:50.938+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: first-dag-v2.task-2 manual__2023-03-04T11:50:47.231477+00:00 [queued]>
[2023-03-04T11:52:50.939+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-04T11:52:50.940+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 6
[2023-03-04T11:52:50.941+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-04T11:52:50.967+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): task-2> on 2023-03-04 11:50:47.231477+00:00
[2023-03-04T11:52:50.974+0000] {standard_task_runner.py:55} INFO - Started process 3035 to run task
[2023-03-04T11:52:50.978+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first-dag-v2', 'task-2', 'manual__2023-03-04T11:50:47.231477+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/tmp/tmpwqhwxnmd']
[2023-03-04T11:52:50.981+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask task-2
[2023-03-04T11:52:51.067+0000] {task_command.py:388} INFO - Running <TaskInstance: first-dag-v2.task-2 manual__2023-03-04T11:50:47.231477+00:00 [running]> on host 00dcc0a33b20
[2023-03-04T11:52:51.176+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ishok
AIRFLOW_CTX_DAG_ID=first-dag-v2
AIRFLOW_CTX_TASK_ID=task-2
AIRFLOW_CTX_EXECUTION_DATE=2023-03-04T11:50:47.231477+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-04T11:50:47.231477+00:00
[2023-03-04T11:52:51.182+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-04T11:52:51.183+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo i'm the second task"]
[2023-03-04T11:52:51.195+0000] {subprocess.py:86} INFO - Output:
[2023-03-04T11:52:51.206+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2023-03-04T11:52:51.207+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2023-03-04T11:52:51.209+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-03-04T11:52:51.223+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-03-04T11:52:51.238+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=first-dag-v2, task_id=task-2, execution_date=20230304T115047, start_date=20230304T115250, end_date=20230304T115251
[2023-03-04T11:52:51.256+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task task-2 (Bash command failed. The command returned a non-zero exit code 2.; 3035)
[2023-03-04T11:52:51.286+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-04T11:52:51.307+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
