[2023-03-04T15:11:02.480+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sl_covid_dag_v1.extract manual__2023-03-04T15:02:52.761551+00:00 [queued]>
[2023-03-04T15:11:02.490+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sl_covid_dag_v1.extract manual__2023-03-04T15:02:52.761551+00:00 [queued]>
[2023-03-04T15:11:02.491+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-04T15:11:02.492+0000] {taskinstance.py:1280} INFO - Starting attempt 5 of 6
[2023-03-04T15:11:02.493+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-04T15:11:02.507+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): extract> on 2023-03-04 15:02:52.761551+00:00
[2023-03-04T15:11:02.513+0000] {standard_task_runner.py:55} INFO - Started process 1484 to run task
[2023-03-04T15:11:02.517+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sl_covid_dag_v1', 'extract', 'manual__2023-03-04T15:02:52.761551+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/sl_covid_dag.py', '--cfg-path', '/tmp/tmpmrfxgh00']
[2023-03-04T15:11:02.520+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask extract
[2023-03-04T15:11:02.595+0000] {task_command.py:388} INFO - Running <TaskInstance: sl_covid_dag_v1.extract manual__2023-03-04T15:02:52.761551+00:00 [running]> on host 00dcc0a33b20
[2023-03-04T15:11:02.678+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ishok
AIRFLOW_CTX_DAG_ID=sl_covid_dag_v1
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-03-04T15:02:52.761551+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-04T15:02:52.761551+00:00
[2023-03-04T15:11:05.162+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sl_covid_dag.py", line 15, in extract
    covid = pd.read_excel(spreadsheet_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1196, in __init__
    "Excel file format cannot be determined, you must specify "
ValueError: Excel file format cannot be determined, you must specify an engine manually.
[2023-03-04T15:11:05.182+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=sl_covid_dag_v1, task_id=extract, execution_date=20230304T150252, start_date=20230304T151102, end_date=20230304T151105
[2023-03-04T15:11:05.212+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task extract (Excel file format cannot be determined, you must specify an engine manually.; 1484)
[2023-03-04T15:11:05.234+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-04T15:11:05.257+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
